name: Build and Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_GITHUB_PAT: ${{ secrets.DATABASE_PAT1 }}

      steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      # Add your deployment steps here